# Taken from https://github.com/banool/aclip/blob/main/.github/filters.yml
force: &force
  - ".force"

ci: &ci
  - *force
  - ".github/**/*"

admin_site:
  - *force
  - *ci
  - 'admin_site/**'

frontend:
  - *force
  - *ci
  - 'frontend/lib/**'
  - 'frontend/ios/**'
  - 'frontend/android/**'
  - 'frontend/web/**'
