name: slsl_dictionary
description: Free video dictionary for Sri Lankan Sign Language

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  carousel_slider:
  collection:
  cupertino_icons:
  dolphinsr_dart:
    git:
      url: https://github.com/banool/dolphhinsr_dart.git
      ref: master
  dots_indicator:
  edit_distance: ^0.5.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_cache_manager:
  flutter_localizations:
    sdk: flutter
  flutter_native_splash:
  go_router: 6.5.9
  http:
  intl:
  launch_review:
  mailto:
  multi_select_flutter:
  path_provider:
  settings_ui:
  shared_preferences:
  system_proxy:
  url_launcher:
  video_player:

dev_dependencies:
  device_info_plus:
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/02-okay-512.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/01-okay.png"

flutter:
  uses-material-design: true
  assets:
    - assets/data/dump.json
