name: slsl_dictionary
description: Free video dictionary for Sri Lankan Sign Language

publish_to: 'none'

version: 1.2.17+148

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider:
  dictionarylib:
    # path: ../../dictionarylib
    git:
      url: https://github.com/banool/dictionarylib.git
      ref: main
  dolphinsr_dart:
    git:
      url: https://github.com/banool/dolphhinsr_dart.git
      ref: master
  dots_indicator:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash:
  go_router:
  http:
  intl:
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  settings_ui:
  shared_preferences:
  url_launcher:
  video_player:

dev_dependencies:
  build_runner: ^2.3.3
  dependency_validator:
  device_info_plus:
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  generate: true

