# Generated by Django 4.1.6 on 2023-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0003_entry_category_delete_mediahandle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="This is a field we might use down the line for some kind of predefined word list feature.",
                max_length=128,
                null=True,
            ),
        ),
    ]
