# Generated by Django 4.1.6 on 2023-02-23 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0004_alter_entry_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"ordering": ["word_in_english"], "verbose_name_plural": "entries"},
        ),
    ]
