# Generated by Django 4.2.1 on 2023-05-30 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0008_alter_video_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="subentry",
            name="region",
            field=models.CharField(
                choices=[("ALL", "All of Sri Lanka"), ("NE", "North East")],
                default="ALL",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="media",
            field=models.FileField(
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
    ]
