# Generated by Django 4.2.1 on 2023-05-31 21:14

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0010_subentry_related_words_alter_definition_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="related_words",
        ),
        migrations.AlterField(
            model_name="subentry",
            name="related_words",
            field=models.CharField(
                blank=True,
                help_text='Optional. Comma separated, for example: "great, really awesome, fantastic"',
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter a comma separated list",
                        regex=re.compile("(^$)|(\\w+)(,\\s*\\w+)*"),
                    )
                ],
            ),
        ),
    ]
