# Generated by Django 4.2.1 on 2023-06-02 11:36

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0011_remove_entry_related_words_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="entry_type",
            field=models.CharField(
                choices=[("WORD", "Word"), ("PHRASE", "Phrase")],
                default="WORD",
                help_text="Whether this entry is a word or a phrase. If unsure, use word.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="subentry",
            name="related_words",
            field=models.CharField(
                blank=True,
                help_text='Optional. Comma separated, for example: "great, really awesome, fantastic"',
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter a comma separated list",
                        regex=re.compile("^(?!.*,$)(\\w+(?:,\\s*\\w(\\w|\\s)*)*)?$"),
                    )
                ],
            ),
        ),
    ]
