# Generated by Django 4.2.1 on 2023-06-08 19:57

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0013_alter_entry_entry_type_alter_video_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subentry",
            name="related_words",
            field=models.CharField(
                blank=True,
                help_text='Optional. Comma separated, for example: "great, really awesome, fantastic"',
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter a comma separated list",
                        regex=re.compile(
                            "^(?!.*,$)([\\w|\\s]+(?:,\\s*\\w(\\w|\\s)*)*)?$"
                        ),
                    )
                ],
            ),
        ),
    ]
