"""
Django settings for slsl_backend project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import typing
from pathlib import Path
from urllib.parse import urlparse

from slsl_backend.secrets import secrets

DEPLOYMENT_MODE_OPTIONS = ["prod", "dev"]

deployment_mode = secrets["deployment_mode"]
if deployment_mode not in DEPLOYMENT_MODE_OPTIONS:
    raise RuntimeError(
        f"DEPLOYMENT_MODE env var set to invalid value: {deployment_mode}"
    )


if deployment_mode == "prod":
    DEBUG = False
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_AGE = 60 * 60  # One hour.
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

if deployment_mode == "dev":
    DEBUG = True

# Whether to run the ffprobe codec/corruption validation on uploaded videos
# (see slsl_backend.validators). Off in dev by default: local dev runs against
# the prod media *filenames* (which aren't on the local disk), so saving an
# entry would re-validate an existing video and crash trying to open a file
# that isn't there. Prod keeps it on. Override per-environment via the
# `validate_media` secret.
VALIDATE_UPLOADED_MEDIA = bool(secrets.get("validate_media", deployment_mode == "prod"))


###########################################################
# The following stuff is generic to all deployment modes. #
###########################################################

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = secrets["secret_key"]

# From here: https://cloud.google.com/python/django/run#csrf_configurations.
CLOUDRUN_SERVICE_URL = os.environ.get("CLOUDRUN_SERVICE_URL")
if CLOUDRUN_SERVICE_URL:
    ALLOWED_HOSTS = [urlparse(CLOUDRUN_SERVICE_URL).netloc]
    CSRF_TRUSTED_ORIGINS = [CLOUDRUN_SERVICE_URL]
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
else:
    ALLOWED_HOSTS = ["*"]

additional_allowed_hosts = secrets.get("additional_allowed_hosts")
if additional_allowed_hosts:
    ALLOWED_HOSTS += additional_allowed_hosts.split(",")

SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "nested_admin",
    "slsl_backend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serve static files (admin CSS/JS) straight from the container.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "slsl_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "slsl_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": secrets["sql_engine"],
        "NAME": secrets["sql_database"],
        "USER": secrets["sql_user"],
        "PASSWORD": secrets["sql_password"],
    }
}

if secrets.get("sql_unix_socket"):
    # If a unix socket is configured, try to connect using that.
    DATABASES["default"]["HOST"] = secrets["sql_unix_socket"]
else:
    # Otherwise try to connect with host + port.
    DATABASES["default"]["HOST"] = secrets["sql_host"]
    DATABASES["default"]["PORT"] = secrets["sql_port"]

# Reuse a DB connection across requests instead of opening a fresh one every
# time. Establishing a Cloud SQL connection is a real per-request cost, and with
# the default (CONN_MAX_AGE=0) every admin page paid it; reusing the connection
# across the requests of an editing session removes that.
#
# Kept modest (60s) on purpose: this runs on Cloud Run with CPU throttled to ~0
# between requests, so a connection held open across an idle gap can be dropped
# by the server side without us being able to keep it alive — and the small
# f1-micro instance has a low connection ceiling, so we don't want connections
# lingering long after a session goes quiet. CONN_HEALTH_CHECKS makes this safe:
# Django validates (and transparently re-opens) the connection at the start of
# each request rather than failing on one that died during the idle period.
DATABASES["default"]["CONN_MAX_AGE"] = 60
DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

# File Storage: Media and static files

STATIC_URL = "/static/"

STATIC_ROOT = "staticfiles"

STORAGES: typing.Dict[str, typing.Dict[str, typing.Any]] = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Static files (Django admin CSS/JS) are served from the Cloud Run container by
# whitenoise in prod — no bucket. collectstatic runs at image build (Dockerfile),
# producing the hashed manifest CompressedManifestStaticFilesStorage needs. Dev
# keeps Django's default static serving (runserver + finders; no manifest).
if deployment_mode == "prod":
    STORAGES["staticfiles"] = {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }

# Media (uploaded sign videos) is served from the Cloudflare R2 mirror
# (slsl-mirror at cdn.srilankansignlanguage.org) via django-storages' S3 backend.
# Gated on the R2 secrets so local dev (which sets none) keeps the filesystem
# default above. This replaced the GCS media bucket + Google Cloud CDN.
if secrets.get("r2_bucket_name"):
    from botocore.config import Config

    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": secrets["r2_bucket_name"],
            "endpoint_url": secrets["r2_endpoint_url"],
            "access_key": secrets["r2_access_key_id"],
            "secret_key": secrets["r2_secret_access_key"],
            "region_name": "auto",
            "location": "media",
            # Serve/display URLs through the CDN custom domain (what the app
            # uses), not the private R2 S3 endpoint. Writes still go to
            # endpoint_url; only url() generation uses this.
            "custom_domain": "cdn.srilankansignlanguage.org",
            # SLSL videos can share filenames, so don't overwrite — append a
            # random suffix instead (mirrors the old GS_FILE_OVERWRITE=False).
            "file_overwrite": False,
            # Objects are served unauthenticated via the CDN (no signed URLs).
            "querystring_auth": False,
            # R2 rejects boto3's default flexible checksums; only send/validate a
            # checksum when the operation actually requires one.
            "client_config": Config(
                request_checksum_calculation="when_required",
                response_checksum_validation="when_required",
            ),
        },
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.ScryptPasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

# Logging

LOG_FILE = os.path.join(SITE_ROOT, "slsl_backend.log")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
        "simple": {"format": "%(asctime)s %(module)s %(message)s"},
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "slsl_backend": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "django.request": {
            "handlers": ["console"],
            "propagate": False,
            "level": "INFO",
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Los_Angeles"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
