# Generated by Django 4.1.6 on 2023-02-23 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="media",
            field=models.FileField(
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "m4v"]
                    )
                ],
            ),
        ),
    ]
