# Generated by Django 4.1.6 on 2023-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0002_alter_video_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="category",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name="MediaHandle",
        ),
    ]
