# Generated by Django 4.1.6 on 2023-02-27 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0007_alter_video_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="media",
            field=models.FileField(
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov"]
                    )
                ],
            ),
        ),
    ]
