# Generated by Django 4.2.1 on 2023-05-31 20:51

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0009_subentry_region_alter_video_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="subentry",
            name="related_words",
            field=models.CharField(
                blank=True,
                help_text='Comma separated, for example: "great, awesome, fantastic"',
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter a comma separated list",
                        regex=re.compile("(^$)|(\\w+)(,\\s*\\w+)*"),
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="language",
            field=models.CharField(
                choices=[("EN", "English"), ("TA", "Tamil"), ("SI", "Sinhala")],
                default="EN",
                max_length=3,
            ),
        ),
    ]
