# Generated by Django 4.2.1 on 2023-06-05 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0012_entry_entry_type_alter_subentry_related_words"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("WORD", "Word"),
                    ("PHRASE", "Phrase"),
                    ("FINGERSPELLING", "Fingerspelling"),
                ],
                default="WORD",
                help_text="Whether this entry is a word or a phrase. If unsure, use word.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="media",
            field=models.FileField(
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "jpg"]
                    )
                ],
            ),
        ),
    ]
