# Generated by Django 4.2.1 on 2024-02-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0014_alter_subentry_related_words"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Please use title case, e.g. "Animals"',
                        max_length=128,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="categories",
            field=models.ManyToManyField(blank=True, to="slsl_backend.category"),
        ),
    ]
