# Generated by Django 4.2.10 on 2024-02-26 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0015_category_entry_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="category",
        ),
    ]
