# Generated by Django 4.2.13 on 2024-10-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("slsl_backend", "0016_remove_entry_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="translation_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="translations",
                to="slsl_backend.definition",
            ),
        ),
    ]
