# Generated by Django 5.2.15 on 2026-06-16 09:35

import django.core.validators
import slsl_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slsl_backend", "0017_definition_translation_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="media",
            field=models.FileField(
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "jpg"]
                    ),
                    slsl_backend.validators.validate_media,
                ],
            ),
        ),
    ]
