# Generated by Django 5.2.15 on 2026-06-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slsl_backend", "0018_alter_video_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="category",
            field=models.CharField(
                choices=[
                    ("AS_A_NOUN", "As a noun"),
                    ("AS_A_VERB_OR_ADJECTIVE", "As a verb or adjective"),
                    ("AS_MODIFIER", "As modifier"),
                    ("AS_QUESTION", "As question"),
                    ("INTERACTIVE", "Interactive"),
                    ("GENERAL_DEFINITION", "General definition"),
                    ("NOTE", "Note"),
                    ("AUGMENTED_MEANING", "Augmented meaning"),
                    ("AS_A_POINTING_SIGN", "As a pointing sign"),
                    ("TRANSLATION", "Translation"),
                ],
                default="AS_A_NOUN",
                max_length=32,
            ),
        ),
    ]
