# Generated by Django 5.2.15 on 2026-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slsl_backend", "0019_alter_definition_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="video",
            name="published",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="video",
            name="recorded",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="video",
            name="researched",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="video",
            name="source",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[("CURRENT", "Current"), ("HISTORICAL", "Historical")],
                default="CURRENT",
                max_length=32,
            ),
        ),
    ]
