# Generated by Django 5.2.15 on 2026-06-18 11:20

from django.db import migrations, models


def backfill_order(apps, schema_editor):
    """Seed `order` so existing data keeps exactly today's display order.

    Before this field, the dump emitted sub-entries id-ascending (per entry) and
    videos newest-first (-id, per sub-entry). Reproduce that as the initial
    `order` so nothing visibly shuffles when this ships; admins can then drag to
    reorder.
    """
    SubEntry = apps.get_model("slsl_backend", "SubEntry")
    Video = apps.get_model("slsl_backend", "Video")
    db = schema_editor.connection.alias

    # Sub-entries: id-ascending within each entry.
    subs = list(SubEntry.objects.using(db).order_by("entry_id", "id"))
    prev = object()
    i = 0
    for se in subs:
        if se.entry_id != prev:
            prev, i = se.entry_id, 0
        se.order = i
        i += 1
    if subs:
        SubEntry.objects.using(db).bulk_update(subs, ["order"], batch_size=500)

    # Videos: newest-first (-id) within each sub-entry.
    vids = list(Video.objects.using(db).order_by("sub_entry_id", "-id"))
    prev = object()
    i = 0
    for v in vids:
        if v.sub_entry_id != prev:
            prev, i = v.sub_entry_id, 0
        v.order = i
        i += 1
    if vids:
        Video.objects.using(db).bulk_update(vids, ["order"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("slsl_backend", "0020_video_note_video_published_video_recorded_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subentry",
            options={"ordering": ["order"], "verbose_name_plural": "sub-entries"},
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="subentry",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        # The columns exist now; seed them to preserve the current order.
        migrations.RunPython(backfill_order, migrations.RunPython.noop),
    ]
