[tool.poetry]
name = "admin-site"
version = "0.1.0"
description = "Admin site for SLSL Dictionary"
authors = ["Daniel Porteous <danielporteous1@gmail.com>"]
packages = [{ include = "slsl_backend" }]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.13"
Django = "^4.2.1"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
gunicorn = "^20.1.0"
django-nested-admin = "^4.0.2"
django-storages = {extras = ["google"], version = "^1.13.2"}
psycopg2-binary = "^2.9.5"

[tool.poetry.dev-dependencies]
autoflake = "^2.0.1"
black = "^23.1.0"
googletrans = "3.1.0a0"
isort = "^5.12.0"
poethepoet = "^0.25.0"
pytest = "^5.2"

[tool.poe.tasks]
isort = "isort . --skip .venv"
black = "poetry run python -m black manage.py . --exclude .venv"

[build-system]
requires = ["poetry-core>=1.4.2"]
build-backend = "poetry.core.masonry.api"
